/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "user_profile_constants.h"

namespace something {

const user_profileConstants g_user_profile_constants;

user_profileConstants::user_profileConstants() {
}

} // namespace

